# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stellarous (Ali Barmaki)
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://stellarous.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
#github_username:  jekyll

remote_theme: daviddarnes/alembic
plugins:
        - jekyll-remote-theme
        - jekyll-seo-tag
        - jekyll-sitemap

# Alembic-specific settings
collections:
        posts:
                output: true
                sort_by: date
                sort_order: descending

defaults:
        - scopre:
                path: ""
                type: posts
                values:
                        layout: post
                        read_time: true

# Social links (customize these)
social:
        - name: Github
          icon: github
          url: https://github.com/stellarous


# Build settings
markdown: kramdown
kramdown:
        math_engine: mathjax
        syntax_highlighter: rouge
